# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    vuepress build
  displayName: 'npm install and build'

- script: |
    git config --global user.email 'codefcbrasil@gmail.com'
    git config --global user.name 'CodeFC'
    git add .
    git commit . -m 'Nova versão compilada da documentação'
  displayName: 'Atualizando documentação'